### ISSUE TITLE
Created At Sort Not Working

### ISSUE THREAD

**Issue by drinkingsouls** [redchamps/extra-sorting-options#2]
Hi Redchamps,
The sort by created_at does not work with Magento 2.4x and ElasticSearch. 
I've found the same for other plugins I've tried. Since Magento search switched to Elastic is seems to not work with created_at.
Is there a solution for this?
Thank you.

**Comment by rav-redchamps** [comment]
Hi @drinkingsouls 

We have recently discontinued this repository & converted it as a paid extension, which is available here https://redchamps.com/extra-sorting-options-magento-2-extension.html

Please try using the new paid extension it works well with 2.4.x & also includes additional "Bestseller" sorting option

**Comment by drinkingsouls** [comment]
The module says updated 8 days ago?

**Comment by rav-redchamps** [comment]
We have  updated ReadME file to include discontinue notice. Please refer to this https://github.com/redchamps/extra-sorting-options/commit/0da52898ca8e93fabec29144ede087fd62d0a755
